// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Tick$ReactHooksTemplate = require("./Tick.bs.js");
var Component2$ReactHooksTemplate = require("./Component2.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Tick$ReactHooksTemplate.make, { }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(Component2$ReactHooksTemplate.make, {
          greeting: "Hello!"
        }), "index2");

/*  Not a pure module */
